### ISSUE TITLE
Refactor DObjects to take a JSONNode parameter in constructors.

### ISSUE THREAD

**Issue by Hedgecoin-** [Magneseus/3x-eh#30]
This is more so I don't forget, but if someone else wants to do this they are more than welcome to go ahead.

The idea is to move any primitive (ie, non-referenced) parameters into a JSON object for constructors.

An example below
```CS
public DTask(DBuilding dBuilding, DResource dOutput, int dMaxPeople, string dName)
{
...
}
```
would become something like
```CS
public DTask(DBuilding dBuilding, DResource dOutput, JSONNode data)
{
    name = data["name"] as string;
    maxPeople = data["maxPeople"] as int;
}
```
We can also do a check to see if it exists and set to defaults otherwise, but it might be nicer to enforce that on the function calling the constructor so they don't have to hunt down unexpected behavior.

**Comment by Magneseus** [comment]
Not presently feasible. (also done kinda by the static LoadFromJSON/SaveFromJSON functions.
