### ISSUE TITLE
Idle task tray resizing improperly.

### ISSUE THREAD

**Issue by Magneseus** [Magneseus/3x-eh#40]
When the tray resizes, the icons aren't positioned properly.

Solutions:
- Change GenerateTaskTrays to account for hidden task slots
- Position TaskTrays to always start at the same position, might make things look more consistent anyways

**Comment by adnanelgalla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resize Idle tray in City Hall depending on merson assgined](https://trello.com/c/0WK67NWX/11-resize-idle-tray-in-city-hall-depending-on-merson-assgined)

**Comment by Magneseus** [comment]
#41
